from .products import Products
from .category import Categories
from .advertisement import advertisement
from .delivery import Delivery
from .status import Status
from .carts import CartItem
from .carts1 import CartItem1
from .Main_TABLE import Main_table
from .User_Detail import User_Detail