# Generated by Django 5.2 on 2025-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_customuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.CharField(blank=True, max_length=50, null=True)),
                ('processing', models.CharField(blank=True, max_length=50, null=True)),
                ('order_confirmed', models.CharField(blank=True, max_length=50, null=True)),
                ('awaiting_fulfillment', models.CharField(blank=True, max_length=50, null=True)),
                ('on_hold', models.CharField(blank=True, max_length=50, null=True)),
                ('pending_shipment', models.CharField(blank=True, max_length=50, null=True)),
                ('shipped', models.CharField(blank=True, max_length=50, null=True)),
                ('in_transit', models.CharField(blank=True, max_length=50, null=True)),
                ('out_for_delivery', models.CharField(blank=True, max_length=50, null=True)),
                ('attempted_delivery', models.CharField(blank=True, max_length=50, null=True)),
                ('delivered', models.CharField(blank=True, max_length=50, null=True)),
                ('completed', models.CharField(blank=True, max_length=50, null=True)),
                ('canceled', models.CharField(blank=True, max_length=50, null=True)),
                ('returned', models.CharField(blank=True, max_length=50, null=True)),
                ('refunded', models.CharField(blank=True, max_length=50, null=True)),
                ('failed', models.CharField(blank=True, max_length=50, null=True)),
                ('delayed', models.CharField(blank=True, max_length=50, null=True)),
                ('lost', models.CharField(blank=True, max_length=50, null=True)),
                ('awaiting_pickup', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
