# Generated by Django 5.2 on 2025-05-15 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_carts_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_table',
            fields=[
                ('user_name', models.CharField(max_length=100)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='attempted_delivery',
        ),
        migrations.RemoveField(
            model_name='status',
            name='awaiting_fulfillment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='awaiting_pickup',
        ),
        migrations.RemoveField(
            model_name='status',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='status',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='status',
            name='delayed',
        ),
        migrations.RemoveField(
            model_name='status',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='status',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='status',
            name='in_transit',
        ),
        migrations.RemoveField(
            model_name='status',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='status',
            name='on_hold',
        ),
        migrations.RemoveField(
            model_name='status',
            name='order_confirmed',
        ),
        migrations.RemoveField(
            model_name='status',
            name='out_for_delivery',
        ),
        migrations.RemoveField(
            model_name='status',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='status',
            name='pending_shipment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='processing',
        ),
        migrations.RemoveField(
            model_name='status',
            name='refunded',
        ),
        migrations.RemoveField(
            model_name='status',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='status',
            name='shipped',
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='orders', max_length=50),
        ),
    ]
