# Generated by Django 5.2 on 2025-05-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_main_table_remove_status_attempted_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='Status_updated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.status'),
        ),
    ]
