# Generated by Django 5.2 on 2025-05-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_main_table_status_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
                ('confirm_password', models.IntegerField()),
            ],
        ),
    ]
