# Generated by Django 5.2 on 2025-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_cartitem_delete_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item_id',
            new_name='productid',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user_name',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='userid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(upload_to='item_images/'),
        ),
    ]
