# Generated by Django 5.2 on 2025-05-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='userid',
            field=models.IntegerField(default=1),
        ),
    ]
