# Generated by Django 5.2 on 2025-05-20 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_main_table_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
