# Generated by Django 5.2 on 2025-05-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_main_table_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='Status_updated',
        ),
        migrations.RemoveField(
            model_name='main_table',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='main_table',
            name='received_date',
        ),
    ]
