# Generated by Django 5.2 on 2025-05-21 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_remove_main_table_status_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='Status_updated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.status'),
        ),
        migrations.AddField(
            model_name='main_table',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='main_table',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
