# Generated by Django 5.2 on 2025-05-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_main_table_status_updated_main_table_order_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
