# Generated by Django 5.2 on 2025-05-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
