# Generated by Django 5.2 on 2025-05-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_remove_main_table_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='Status_updated',
        ),
    ]
