# Generated by Django 5.2 on 2025-05-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_remove_main_table_status_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='Status_updated',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, to='stores.status'),
        ),
    ]
