# Generated by Django 5.2 on 2025-05-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_main_table_status_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='Status_updated',
        ),
        migrations.AddField(
            model_name='main_table',
            name='Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.status'),
        ),
    ]
