# Generated by Django 5.2 on 2025-05-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_remove_main_table_status_updated_main_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='Status',
        ),
    ]
