# Generated by Django 5.2 on 2025-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_remove_main_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='order_date',
            field=models.IntegerField(default=1),
        ),
    ]
