# Generated by Django 5.2 on 2025-05-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_main_table_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='order_date',
        ),
    ]
