# Generated by Django 5.2 on 2025-05-25 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0027_remove_main_table_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='Status',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, to='stores.status'),
        ),
    ]
