# Generated by Django 5.2 on 2025-05-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_remove_main_table_status_main_table_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table',
            name='Status1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.status'),
        ),
    ]
