# Generated by Django 5.2 on 2025-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_alter_main_table_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='Status1',
        ),
        migrations.AddField(
            model_name='main_table',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
