# Generated by Django 5.2 on 2025-05-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_remove_main_table_status1_main_table_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='age',
        ),
        migrations.CreateModel(
            name='Main_table1',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=1)),
                ('user_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('age', models.IntegerField(default=1)),
                ('Status1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.status')),
            ],
        ),
    ]
