# Generated by Django 5.2 on 2025-05-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_remove_main_table_age_main_table1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table1',
            name='Status1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.categories'),
        ),
    ]
