# Generated by Django 5.2 on 2025-05-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0033_alter_main_table1_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table1',
            name='Status1',
        ),
    ]
