# Generated by Django 5.2 on 2025-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0034_remove_main_table1_status1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_table1',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
