# Generated by Django 5.2 on 2025-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_delete_main_table1_cartitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem1',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='item_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
    ]
