# Generated by Django 5.2 on 2025-05-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0036_cartitem1_remove_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='order_date',
            field=models.IntegerField(default=1),
        ),
    ]
