# Generated by Django 5.2 on 2025-05-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0037_main_table_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
