# Generated by Django 5.2 on 2025-06-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0038_main_table_received_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_table',
            old_name='order_date',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='main_table',
            name='received_date',
        ),
    ]
